name: 'Cynalytica Container image scan'
description: 'Scan container images for vulnerabilities and issues from scan'
branding:
  icon: 'aperture'
  color: 'orange'
inputs:
  image-names:
    description: 'Docker images to scan, comma or space seperated image list to scan'
    required: true
  severity-threshold:
    description: '(Optional) Minimum severity threshold set to control flagging of the vulnerabilities found during the scan. The available levels are: (UNKNOWN, LOW, MEDIUM, HIGH, CRITICAL); if you set the severity-threshold to be `MEDIUM` every CVE found of a level higher than or equal to `MEDIUM` would be displayed'
    required: false
    default: 'MEDIUM'
  wont-fix-label:
    description: "Label to identify the closed issues that should not be re-opened from this action."
    default: "wontfix"
    required: true
  no-fix-label:
    description: "Label to use to tag CVE's that have no known fix at the moment"
    default: "no-fix"
    required: true
  is-fixed-label:
    description: "User applied label to prevent issues from being reopened."
    default: "fixed"
    required: true
  max-create-retry:
    description: "Maximum number of times to try and create an issue. otherwise just call it a day."
    default: "2"
    required: false
  username:
    description: 'Username to authenticate to the Docker registry'
    required: false
  password:
    description: 'Password to authenticate to the Docker registry'
    required: false
  token:
    description: 'Github token'
    default: ${{ github.token }}
    required: true
  run-quality-checks:
    description: 'Add additional checks to ensure the image is secure and follows best practices and CIS standards'
    default: 'true'
    required: false
  run-issue-create:
    description: 'Create issues on the repo instead of using SARIF reports.'
    default: 'false'
    required: false


outputs:
  scan-report-path:
    description: 'File path where the scan results are stored'
  sarif-report-path:
    description: 'File path where the scan results are stored'
  audit-reports-path:
    description: 'File path where the scan results are stored'
  check-run-url:
    description: 'URL of the check run. Overview about finding of vulnerabilities and best-practices.'

runs:
  using: 'node12'
  main: 'lib/main.js'
