name: "Run unit tests."
on: # rebuild any PRs and main branch changes
  pull_request:
    branches:
      - master
      - 'releases/*'
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build: # make sure build/ci works properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm install
     - run: npm test

